In [0]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression 

In [0]:
df = pd.read_csv('train.csv')
df2 = pd.read_csv('Q1_Mushroom_test.csv')

In [0]:
df.head()

class cap-shape cap-surface  ... spore-print-color population habitat
0     e         x           y  ...                 n          v       d
1     e         x           f  ...                 k          a       g
2     e         x           y  ...                 n          v       d
3     p         f           f  ...                 h          v       d
4     p         x           y  ...                 k          s       u

[5 rows x 23 columns]

In [0]:
print(df2.head())
XTest = df2.to_numpy()

  cap-shape cap-surface cap-color  ... spore-print-color population habitat
0         f           y         n  ...                 w          v       d
1         x           s         e  ...                 w          v       l
2         f           s         w  ...                 n          a       g
3         b           y         y  ...                 k          n       m
4         f           f         g  ...                 n          a       g

[5 rows x 22 columns]


In [0]:
# Target Variable
Y = df['class']
print(Y.shape)
Y.head()

(7124,)


0    e
1    e
2    e
3    p
4    p
Name: class, dtype: object

In [0]:
# Features
X = df.iloc[:,1:]
print(X.shape)
X.head()

(7124, 22)


cap-shape cap-surface cap-color  ... spore-print-color population habitat
0         x           y         g  ...                 n          v       d
1         x           f         w  ...                 k          a       g
2         x           y         g  ...                 n          v       d
3         f           f         g  ...                 h          v       d
4         x           y         w  ...                 k          s       u

[5 rows x 22 columns]

In [0]:
X.describe()
x = X.to_numpy()
y = Y.to_numpy()

In [0]:
XTrain,XVal,YTrain,YVal = train_test_split(x,y,test_size=0.1,random_state=0)

In [0]:
print(XTrain.shape)
print(XVal.shape)
print(YTrain.shape)
print(YVal.shape)

(6411, 22)
(713, 22)
(6411,)
(713,)


In [0]:
print(YVal[:10])

['p' 'e' 'e' 'p' 'p' 'e' 'p' 'e' 'e' 'p']


In [0]:
# OneHotEncoding categorical variables
encoder = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xtrain = encoder.fit_transform(x)
Xval = encoder.transform(XVal)
Xtest = encoder.transform(XTest)

In [0]:
label_encoder = LabelEncoder()
Ytrain = label_encoder.fit_transform(y)
Yval = label_encoder.transform(YVal)

In [0]:
print(Ytrain[:10])
print(y[:10])

[0 0 0 1 1 1 0 1 0 0]
['e' 'e' 'e' 'p' 'p' 'p' 'e' 'p' 'e' 'e']


In [0]:
# 0 = e
# 1 = p

In [0]:
print(YVal[:10])
print(Yval[:10])

['p' 'e' 'e' 'p' 'p' 'e' 'p' 'e' 'e' 'p']
[1 0 0 1 1 0 1 0 0 1]


In [0]:
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)

(7124, 117)
(1000, 117)
(7124,)


In [0]:
classifier = GradientBoostingClassifier(random_state=0)
classifier.fit(Xtrain,Ytrain)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [0]:
print(classifier.predict(Xval[:15]))
print(Yval[:15])

[1 0 0 1 1 0 1 0 0 1 0 0 0 0 1]
[1 0 0 1 1 0 1 0 0 1 0 0 0 0 1]


In [0]:
print(classifier.score(Xval,Yval))

1.0


In [0]:
Ytest = classifier.predict(Xtest)
print(type(Ytest))
print(Ytest.shape)
d = {0:'e',1:'p'}
labels = []
for i in range(Ytest.shape[0]):
  labels.append(d[Ytest[i]])

<class 'numpy.ndarray'>
(1000,)


In [0]:
with open("Q1.txt", "w") as op:
    for item in labels:
      op.write(str(item)+'\n')